# Page settings
baseurl = "localhost:1313"
title = "subs·GURU"
languageCode = "en-us"
theme = "hugo-elate-theme"
publishDir = "docs"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = "fabrice@sb.am"
  # Navigation
  [params.navigation]
    brand = "subs·GURU"
    intro = "Get started"
    testimonials = "About subs·GURU"
    services = "Documentation"
    about = "Community"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "subs·GURU"
    subtitle = "subs·GURU is a all inclusive solution software to allowing you to focus on your customer thanks to all of its features. Indeed, subsGURU manages your accounting, the contract’s establishment, billing and much more. subs·GURU is a complete software, we learned about issues start-up have that’s why, inside subs·GURU panel, you’re able to personalize every contracts, every options is considered, from pricing to units you want to include in the contract.  "
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]
  title = "Get started"
  description = "subs·GURU is ready to use and improve, come to our GitHub and you'll find everything you'll need to develop more features and use the software."


  [[params.intro.item]]
    title = "OpenSource"
    description = "subs·GURU is an Open Source Software because we trust in everyone. Each of us got some talentd and we offer you to help us to continue to build the most complet software as possible."

    url = "https://github.com/subs-guru"
    button = "Join us"
    icon = "icon-github"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Join Us"
    description = "You can add features needed, option to wanna see, you're totally free in your proposition and your work. Don't forget to join us our community Slack and GitHub ! "
    url = "https://now-examples-slackin-tcqqdubmyx.now.sh/"
    button = "Join us"
    icon = "icon-slack"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Billing"
    description = "You have to build the customer's subscription plan, choose about options to include in the contract, to establish the variable price or let the fixed price written on subs·GURU's panel."
    url = "#"
    button = "Click Me"
    icon = "icon-calculator"
    img = "img_10.jpg"

    [[params.intro.item]]
    title = "Stat's View"
    description = "Then, you must fix the payment schedule (right here, you can, as before, choose between general schedule settings or adjust with customer's wishes."
    url = "#"
    button = "Click Me"
    icon = "icon-graph"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Building sub's plan"
    description = "Once the firsts steps are completed, you can manage customer's accounting, establish his invoice that he can receive by an e-mail in PDF format."
    url = "#"
    button = "Click Me"
    icon = "icon-paper"
    img = "img_10.jpg"

    [[params.intro.item]]
    title = "Later"
    description = "Later, you can have a large view on metrics like MRR, CHURN, ARPU and more to allow you to correct if any trouble happens before it takes a large proportion."
    url = "#"
    button = "Click Me"
    icon = "icon-rocket"
    img = "img_7.jpg"


  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?time_continue=94&v=SCA9_0UtzSg"


  # Testimonials section
  [params.testimonials]
    enable = true
    title = "About subs·GURU"
    description = "subs·GURU is an open source software and mainly edited for subscriptions billing start-ups."

    [[params.testimonials.item]]
      quote = "<strong>What issues ?</strong><br><br>subs·GURU manages accounting issues, plans establishement, including options and different prices which can be ajust; but also several payment methods, invoicing editing ans automates the PDF's bill sending."
      person = ''
      img = ""
      alt = ""


    [[params.testimonials.item]]
      quote = "<strong>For who ?</strong> <br><br>Every start-ups who got a business aboute subscriptions billing can benefit subs·GURU, like SaaS software's editors, IOT services, OEM platforms. Accountments, customers communities/unions and even new industry's economic models can use our software."
      person = ''
      img = ""
      alt = ""


    [[params.testimonials.item]]
      quote = "<strong>Why do you published an open source software ?</strong> <br><br> We trust in the community's talent, in all of you. We're sure that you can help us to develop more features to do a more complete software."
      person = ''
      img = ""
      alt = ""
      

  # Services section
  [params.services]
    enable = true
    title = "Documentation"
    description = "For more information about us !"

    [[params.services.item]]
      title = '<a href="https://artie.gitbooks.io/subsguru/content/features.html" target="_blank">subs·GURU </a>'
      description = "subs·GURU was built to allow users to focus on customers' values thanks to all the features included"
      icon = "icon-anchor"

    [[params.services.item]]
      title = '<a href="https://artie.gitbooks.io/subsguru/content/organisation.fr/organization.html" target="_blank">Organization</a>'
      description = "A customer can have some subscriptions, but these subscriptions can be organized in many ways."
      icon = "icon-layers2"

    [[params.services.item]]
      title = '<a href="https://artie.gitbooks.io/subsguru/content/data-structure.fr/data-structure.html" target="_blank">Data structure</a>'
      description = "A contract define a commercial relationship with the customers, on a defined period. A subscription defines details which will be billed to the customer (can have personalized fields. A period is an contract's iteration (beginning and duration are defined by the contract). Period is manages automatically."
      icon = "icon-video2"

      [[params.services.item]]
      title = '<a href="https://artie.gitbooks.io/subsguru/content/create-your-plans.fr/create-your-plans.html" target="_blank">Create your plans</a>'
      description = "To configure your system, you have to create the complete configuration which define your plans. You'll find just below global subscriptions ans plan's use explications."      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "Community"
    description = "For us, everyone is important, that's why we want to build a linked community around subsGURU thanks to our slack and incoming forum."

    [[params.about.item]]
      name = "Github"
      position = ""
      description = "Join us on our GitHub to find all the resources you need to help us develop more features and more."
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-github", "https://github.com/subs-guru/subs-guru-doc"]
      ]
      

    [[params.about.item]]
      name = "Slack"
      position = ""
      description = "Also, join our community slack to talk and share with the others talents who wanna help us."
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-slack", "https://now-examples-slackin-tcqqdubmyx.now.sh/"]
      ]
      

    [[params.about.item]]
      name = "Our social networks"
      position = ""
      description = "And finally, join our social networks to stay aware about all the subs·GURU actuality."
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "https://twitter.com/SubsGuru?lang=fr"],
        ["icon-facebook", "https://www.facebook.com/SubsGURU/"],
        ["icon-linkedin", "https://www.linkedin.com/in/subs-guru-b0b357160/"],
        ["icon-instagram", "https://www.instagram.com/subsguru/"]
      ]
      

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Contact"
    description = "For more information, you can fill the form and we'll anwser quicker as possible !"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "72 rue de la République, Seine Innopolis,<br>76140 Le Petit-Quevilly"],
        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "info@subsguru.fr"],
        ["icon-globe", '<a href="#" target="_blank">subs·GURU </a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    
    links = [
        ["icon-twitter", "https://twitter.com/SubsGuru?lang=fr"],
        ["icon-facebook", "https://www.facebook.com/SubsGURU/"],
        ["icon-youtube", "https://www.youtube.com/channel/UCYULEbaaQPxZq1hrkkxA3QA"],
        ["icon-github", "https://github.com/subs-guru/subs-guru-doc"],
        ["icon-instagram", "https://www.instagram.com/subsguru/"],
        ["icon-linkedin", "https://www.linkedin.com/in/subs-guru-b0b357160/"],
        ["icon-slack", "https://now-examples-slackin-tcqqdubmyx.now.sh/"]
      ]
